### ISSUE TITLE
Feedback on proposal

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI_522_Income_Prediction#7]
@olivia-lin and @ksm45 , you have chosen an interesting question and I look forward to reading more on your analysis! Here are some improvement points and minor suggestions for your project.

**Reasoning**
- Keep in mind that your readme is the landing page for someone examining your analysis. Therefore, you can do some additions that would make the readme more informative and intriguing for a visitor. In particular, you can
	- include a brief introduction about the context and your motivation to do such analysis.
	- explain the data a bit more in detail, state the variables included, or print the head of the data table in the main readme. Including the link to the data source is a good idea, but still explaining the data in your repository is needed.

- I believe you can briefly mention why you chose a decision tree in your analysis. Why do you think this model suitable for your analysis?

**Mechanics**

- The `src/` folder is for your scripts. Since you have that, you should not also have a `scripts/` folder. Your scripts should be in your `src/` folder. You might want to follow the repo structure as outlined [here](https://github.ubc.ca/MDS-2018-19/DSCI_522_dsci-workflows_students/issues/10) by Tiffany. Every repo might be different a bit, but I believe it is better follow a standard structure as you'll see in most data science projects.

**Minor Suggestions:**

- I would recommend taking "DSCI_522" out of the name of your project. But if you like it this way, no problem.

I hope this feedback is helpful in improving your project. Please let me know if you have any questions. Good luck!

**Comment by olivia-lin** [comment]
Fixed, thanks!
